SELECT H.HACKER_ID AS HID, H.NAME AS HN, COUNT(*) AS TOTAL FROM HACKERS H
LEFT JOIN CHALLENGES C ON C.HACKER_ID = H.HACKER_ID
GROUP BY HID, HN
HAVING(
    TOTAL = (SELECT COUNT(*) FROM CHALLENGES GROUP BY HACKER_ID ORDER BY COUNT(*) DESC LIMIT 1)
    OR TOTAL IN (SELECT * FROM (SELECT COUNT(*) AS CT FROM CHALLENGES GROUP BY HACKER_ID) A
    GROUP BY A.CT HAVING (COUNT(*) = 1))
)
ORDER BY TOTAL DESC, HID
