SELECT NAME
FROM (
    SELECT
        S.NAME,
        P.SALARY,
        (SELECT SALARY FROM PACKAGES WHERE ID = F.FRIEND_ID) AS FRIEND_SALARY
    FROM STUDENTS S, FRIENDS F, PACKAGES P WHERE S.ID = F.ID AND F.ID = P.ID ) AS A
WHERE SALARY < FRIEND_SALARY
ORDER BY FRIEND_SALARY
