SELECT X, Y FROM Functions F1
WHERE EXISTS (SELECT X, Y FROM Functions F2 WHERE F2.Y = F1.X
    AND F2.X = F1.Y AND F2.X > F1.X AND X != Y)
UNION
SELECT X, Y FROM Functions F1 WHERE X = Y GROUP BY X, Y
HAVING COUNT(*) > 1
ORDER BY X
